config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root 'books#index'

  get 'books' => 'books#my_books'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "70x70>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # def my_books
  #   @books = Book.find(params[:id])
  # end

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :summary, :genre, :avg_rating, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="form-group">
    <%= f.label :avg_rating %><br>
    <%= f.number_field :avg_rating %>
  </div>
  <div class="form-group">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>

  <div class="form-group">
    <p>Image of the book cover: </p>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container opaqueContainer">
  <h3>Please edit the details of the book below:</h3>
  <%= render 'form' %>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>



<!-- insert a h2 selection of genres here -->

<div class="row">
  <% @books.each do |book| %>
      <div class="panel panel-default col-md-4">
        <div class="panel-heading">
          <div class="pull-right">
            <% if book.avatar.exists? %>
              <%= image_tag book.avatar.url(:thumb) %>
            <% else %>
              <%= image_tag "book_cover.jpg", class:"book-thumb"%>
            <% end %>
          </div>
          <h3><%= link_to book.title.titleize, book %></h3>
          <h4>by <%= book.author.titleize %></h4>
        </div>
        <div class="panel-body">
          <p><%= truncate(book.summary,length:125,separator:' ') %></p>
          <p><%= link_to 'Read more', book %> </p>
          <p><%= book.avg_rating %> out of 5.0</p>
        </div>
        <% if current_user == book.user %>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_book_path(book), class:"btn btn-default" %>
            <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          </div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/books/my_books.html.erb
<div class="row">
  <% @books.each do |book| %>
      <div class="panel panel-default col-md-4">
        <div class="panel-heading">
          <div class="pull-right">
            <%= image_tag book.avatar.url(:thumb) %>
          </div>
          <h3><%= link_to book.title.titleize, book %></h3>
          <h4>by <%= book.author.titleize %></h4>
        </div>
        <div class="panel-body">
          <p><%= truncate(book.summary,length:125,separator:' ') %></p>
          <p><%= link_to 'Read more', book %> </p>
          <p><%= book.avg_rating %> out of 5.0</p>
        </div>
        <% if current_user == book.user %>
          <div class="panel-footer">
            <%= link_to 'Edit', edit_book_path(book), class:"btn btn-default" %>
            <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          </div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="container opaqueContainer">
  <h3>Please provide details about the book you are adding below:</h3>
  <%= render 'form' %>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="pull-right">
        <%= image_tag @book.avatar.url(:thumb) %>
      </div>
      <h3><%= @book.title.titleize %></h3>
      <h4>by <%= @book.author.titleize %></h4>
    </div>
    <div class="panel-body">
      <p><%= @book.summary %></p>
      <p><strong>Average Rating:  </strong><%= @book.avg_rating %> out of 5.0</p>
    </div>
    <!-- ???? -->
    <% if current_user == @book.user %>
      <div class="panel-footer">
        <%= link_to 'Edit', edit_book_path(book), class:"btn btn-default" %>
        <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Virtual Book Swap</title>

  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "shared/nav" %>
  <div class="page-content"><%= yield %></div>

</body>
</html>

app/views/shared/_nav.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "All Books", books_path, class:"navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'New Book', new_book_path %></li>
          <!-- #<li><%= link_to 'My Books', my_books_path %></li> -->
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>